config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  def self.queryAll(query)
    self.where("name LIKE ? OR address LIKE ? OR phrase LIKE ? OR ranking LIKE ?  OR spell LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    if params[:query].present?
      @users = User.queryAll(params[:query])
    else
      @pagy, @users = pagy(User.all)
    end

    respond_to do |format|
      if turbo_frame_request? && turbo_frame_request_id == "search" #verifica se retornou um turbo_frame
        format.html { render partial: "users_table", locals: { users: @users } }
      else
        format.html
      end
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :address, :phrase, :ranking, :spell)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabelaTeste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :phrase, style: "display: block" %>
    <%= form.text_area :phrase %>
  </div>

  <div>
    <%= form.label :ranking, style: "display: block" %>
    <%= form.text_field :ranking %>
  </div>

  <div>
    <%= form.label :spell, style: "display: block" %>
    <%= form.text_field :spell %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_users_table.html.erb
<div id="">
  <%= turbo_frame_tag 'search' do %>

    <p>
      <% if params[:query].present? %>
        <%= "Total de resultados: #{users.all.count}" %>
      <% end %>
    </p>

    <table class="table  table-bordered">
      <thead class="table-dark">
        <tr>
          <th scope="col"><strong>ID</strong></th>
          <th scope="col"><strong>Name</strong></th>
          <th scope="col"><strong>Address</strong></th>
          <th scope="col"><strong>Phrase</strong></th>
          <th scope="col"><strong>Ranking</strong></th>
          <th scope="col"><strong>Spell</strong></th>
        </tr>
      </thead>

      <% users.each do |user| %>
        <tbody>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= user.name %></td>
            <td><%= user.address %></td>
            <td><%= user.phrase %></td>
            <td><%= user.ranking %></td>
            <td><%= user.spell %></td>
          </tr>
        </tbody>
      <% end %>

    </table>
  <% end %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="users" class="container">
  <%= form_with url: users_path, method: :get, data: { turbo_frame: 'search', controller: 'search', action: 'keyup->search#perform' } do |f| %>
    <%= f.label "Search:" %>
    <%= f.text_field :query %>
  <% end %>

  <h1 class="text-center">Champion List</h1>
  <%= link_to "New user", new_user_path %>

  <%= render "users_table", users: @users %>

  <%== pagy_nav(@pagy) %>

</div>